/*
 * SD_Card.c
 *
 *  Created on: Mar 12, 2024
 *      Author: suriya.prakash
 */

#include <HTML_Code.h>


/**********************************************GERMAN*******************************************************/
const char GERMAN[] =
		"<!DOCTYPE html>\n"
		"<html lang=\"en\">\n"
		"<head>\n"
		"<meta charset=\"UTF-8\">\n"
		"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
		"<title>Graphical presentation GERMAN format</title>\n"
		"<style>\n"
		"body {\n"
		"margin: 0;\n"
		"padding: 0;\n"
		"display: flex;\n"
		"align-items: center;\n"
		"justify-content: center;\n"
		"height: 100vh;\n"
		"}\n"
		"#outer_box {\n"
		"top: 80%;\n"
		"width: 98%;\n"
		"height: 70vh;\n"
		"overflow: auto;\n"
		"border: 2px solid #000;\n"
		"position: absolute;\n"
		"}\n"
		"#outer_box1 {\n"
		"top: 2%;\n"
		"width: 98%;\n"
		"height: 70vh;\n"
		"overflow: auto;\n"
		"border: 2px solid #000;\n"
		"position: absolute;\n"
		"}\n"
		"#outer_box2 {\n"
		"top: 157%;\n"
		"width: 98%;\n"
		"height: 70vh;\n"
		"overflow: auto;\n"
		"border: 2px solid #000;\n"
		"position: absolute;\n"
		"}\n"
		"#outer_box3 {\n"
		"top: 234%;\n"
		"width: 98%;\n"
		"height: 70vh;\n"
		"overflow: auto;\n"
		"border: 2px solid #000;\n"
		"position: absolute;\n"
		"}\n"
		"#outer_box4 {\n"
		"top: 310%;\n"
		"width: 98%;\n"
		"height: 70vh;\n"
		"overflow: auto;\n"
		"border: 2px solid #000;\n"
		"position: absolute;\n"
		"}\n"
		"#outer_box5 {\n"
		"top: 385%;\n"
		"width: 98%;\n"
		"height: 70vh;\n"
		"overflow: auto;\n"
		"border: 2px solid #000;\n"
		"position: absolute;\n"
		"}\n"
		"#outer_box6 {\n"
		"top: 460%;\n"
		"width: 98%;\n"
		"height: 70vh;\n"
		"overflow: auto;\n"
		"border: 2px solid #000;\n"
		"position: absolute;\n"
		" }\n"
		"#outer_box7 {\n"
		"top: 535%;\n"
		"width: 98%;\n"
		"height: 70vh;\n"
		"overflow: auto;\n"
		"border: 2px solid #000;\n"
		"position: absolute;\n"
		"}\n"
		"#outer_box8 {\n"
		"top: 700%;\n"
		"width: 98%;\n"
		"height: 70vh;\n"
		"overflow: auto;\n"
		"border: 2px solid #000;\n"
		"position: absolute;\n"
		"}\n"
		"#outer_box9 {\n"
		"top: 800%;\n"
		"width: 98%;\n"
		"height: 70vh;\n"
		"overflow: auto;\n"
		"border: 2px solid #000;\n"
		"position: absolute;\n"
		"}\n"
		"#tableContainer {\n"
		"max-height: 600px;\n"
		"overflow-y: auto;\n"
		"}\n"
		"table {\n"
		"border-collapse: collapse;\n"
		"width: 100%;\n"
		"table-layout: fixed;\n"
		"margin-bottom: 20px;\n"
		"}\n"
		"th, td {\n"
		"border: 1px solid #dddddd;\n"
		"text-align: left;\n"
		"padding: 8px;\n"
		"}\n"
		"th{\n"
		"background-color: #f2f2f2;\n"
		"}\n"
		"#curve_chart {\n"
		"top: 70%;\n"
		"width: 98%;\n"
		"height: 70vh;\n"
		"overflow: auto;\n"
		"}\n"
		"#curve_chart2 {\n"
		"top: 70%;\n"
		"width: 98%;\n"
		"height: 70vh;\n"
		"}\n"
		"#curve_chart3 {\n"
		"top: 70%;\n"
		"width: 98%;\n"
		"height: 70vh;\n"
		"}\n"
		"#curve_chart4 {\n"
		"top: 70%;\n"
		"width: 98%;\n"
		"height: 70vh;\n"
		"}\n"
		"#curve_chart5 {\n"
		"top: 70%;\n"
		"width: 98%;\n"
		"height: 70vh;\n"
		"}\n"
		"#curve_chart6 {\n"
		"top: 70%;\n"
		"width: 98%;\n"
		"height: 70vh;\n"
		"}\n"
		"#fileInputContainer {\n"
		"position: absolute;\n"
		"top: 10px;\n"
		"left: 10px;\n"
		"background-color: #fff;\n"
		"padding: 10px;\n"
		"border: 1px solid #ccc;\n"
		"border-radius: 5px;\n"
		"box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\n"
		"}\n"
		"#container {\n"
		"perspective: 800px;\n"
		"width: 300px;\n"
		"height: 300px;\n"
		"position: absolute;\n"
		"top: 30%;\n"
		"left: 40%;\n"
		"}\n"
		"#refresh-button {\n"
		"      padding: 5px 8px;\n"
		"      color: #fff;\n"
		"     border: 1px solid #ccc;\n"
		"background-color: #3498db;   \n"
		"      font-size: 13px;\n"
		"      border-radius: 5px;\n"
		"    }\n"
		"#model {\n"
		"width: 100%;\n"
		"height: 100%;\n"
		"background-color: #3498db;\n"
		"position: absolute;\n"
		"transform-style: preserve-3d;\n"
		"transition: transform 1s ease-in-out;\n"
		"}\n"
		".axis {\n"
		"position: absolute;\n"
		"width: 2px;\n"
		"height: 100px;\n"
		"background-color: #e74c3c;\n"
		"transform-origin: 50% 100%;\n"
		"}\n"
		".axis-x {\n"
		"left: 50%;\n"
		"top: 50%;\n"
		"transform: translateX(-50%) translateY(-100%) rotateX(90deg);\n"
		"background-color: #25161a;\n"
		"}\n"
		".axis-y {\n"
		"left: 50%;\n"
		"top: 50%;\n"
		"transform: translateX(-50%) translateY(-50%)rotateZ(-90deg);\n"
		"background-color: #e74c3c;\n"
		"}\n"
		".axis-z {\n"
		"left: 50%;\n"
		"top: 50%;\n"
		"transform: translateX(-50%) translateY(-50%) rotateZ(0deg);\n"
		"background-color: #68f4c6;\n"
		"}\n"
		"#play-button {\n"
		"position: absolute;\n"
		"top: 100px;\n"
		"left:20%;\n"
		"transform: translateX(-50%);\n"
		"padding: 10px;\n"
		"background-color: #2ecc71;\n"
		"color: #fff;\n"
		"cursor: pointer;\n"
		"}\n"
		"#play-button1 {\n"
		"position: absolute;\n"
		"top: 100px;\n"
		"left: 40%;\n"
		"transform: translateX(-50%);\n"
		"padding: 10px;\n"
		"background-color: #2ecc71;\n"
		"color: #fff;\n"
		"cursor: pointer;\n"
		"}\n"
		"#pause-button {\n"
		"position: absolute;\n"
		"top: 100px;\n"
		"left: 60%;\n"
		"transform: translateX(-50%);\n"
		"padding: 10px;\n"
		"background-color: #e74c3c;\n"
		"color: #fff;\n"
		"cursor: pointer;\n"
		"}\n"
		"#reset-button {\n"
		"position: absolute;\n"
		"top: 100px;\n"
		"left: 80%;\n"
		"transform: translateX(-50%);\n"
		"padding: 10px;\n"
		"background-color: #3498db;\n"
		"color: #fff;\n"
		"cursor: pointer;\n"
		"}\n"
		"</style>\n"
		"</head>\n"
		"<body>\n"
		"<div id=\"outer_box1\">\n"
		"<div id=\"fileInputContainer\">\n"
		"  <button id=\"refresh-button\" onclick=\"refreshPage()\">Refresh</button>\n"
		"<input type=\"file\" id=\"fileInput\" accept=\".csv\">\n"
		"<div id=\"tableContainer\">\n"
		"</div>\n"
		"</div>\n"
		"</div>\n"
		"<div id=\"outer_box\">\n"
		"<div id=\"curve_chart\"></div>\n"
		"</div>\n"
		"<div id=\"outer_box2\">\n"
		"<div id=\"container\">\n"
		"<div id=\"model\">\n"
		"<div class=\"axis axis-x\"></div>\n"
		"<div class=\"axis axis-y\"></div>\n"
		"<div class=\"axis axis-z\"></div>\n"
		"</div>\n"
		"</div>\n"
		"<p align=\"center\"><b>Time:</b> <span style=\"font-weight:bold;\" id=\"clickCount\">0</span></p>\n"
		"<p style=\"bottom: 0; width: 100%; text-align: center;\">\n"
		"<span style=\"color: #25161a;\">(X-AXIS)</span>\n"
		"<span style=\"color: #e74c3c;\">(Y-AXIS)</span>\n"
		"<span style=\"color: #68f4c6;\">(Z-AXIS)</span>\n"
		"</p>\n"
		"<div id=\"play-button\" onclick=\"playAnimation()\">CLICK</div>\n"
		"<div id=\"play-button1\" onclick=\"autoPlayAnimation()\">AUTO_PLAY</div>\n"
		"<div id=\"pause-button\" onclick=\"pauseAnimation()\">PAUSE</div>\n"
		"<div id=\"reset-button\" onclick=\"resetAnimation()\">RESET</div>\n"
		"</div>\n"
		"<div id=\"outer_box3\">\n"
		"<div id=\"curve_chart2\"></div>\n"
		"</div>\n"
		"<div id=\"outer_box4\">\n"
		"<div id=\"curve_chart3\"></div>\n"
		"</div>\n"
		"<div id=\"outer_box5\">\n"
		"<div id=\"curve_chart4\"></div>\n"
		"</div>\n"
		"<div id=\"outer_box6\">\n"
		"<div id=\"curve_chart5\"></div>\n"
		"</div>\n"
		"<div id=\"outer_box7\">\n"
		"<div id=\"curve_chart6\"></div>\n"
		"</div>\n"
		"<script type=\"text/javascript\" src=\"https://www.gstatic.com/charts/loader.js\"></script>\n"
		"<script type=\"text/javascript\">\n"
		"google.charts.load(\'current\', {\'packages\':[\'corechart\']});\n"
		"google.charts.setOnLoadCallback(handleFile);\n"
		"document.getElementById(\'fileInput\').addEventListener(\'change\', handleFile);\n"
		"const firstColumnValues = [];\n"
		"const userValues = [];\n"
		"const axis = [];\n"
		"const temp = [];\n"
		"const freq = [];\n"
		"const sleep = [];\n"
		"const Rwater = [];\n"
		"const pressure = [];\n"
		"let d1 = [];\n"
		"let d2 = [];\n"
		"let d3 = [];\n"
		"let d4 = [];\n"
		"let d5=[];\n"
		"let d6=[];\n"
		"let d7=[];\n"
		"let d8=[];\n"
		"let d9=[];\n"
		"let d10=[];\n"
		"let d11=[];\n"
		"let d12=[];\n"
		"let data = [];\n"
		"let d =[];\n"
		"let t = [];\n"
		"let f =[];\n"
		"let s=[];\n"
		"let rw=[];\n"
		"let pre=[];\n"
		"let lines = []; \n"
		"let currentTimeIndex = 0;\n"
		"function handleFile(event) {\n"
		"const file = event.target.files[0];\n"
		"if (file) {\n"
		"const reader = new FileReader();\n"
		"google.charts.load(\'current\', {\'packages\':[\'corechart\']});\n"
		"google.charts.setOnLoadCallback(handleFile);\n"
		"reader.onload = function(e) {\n"
		"const csvData = e.target.result;\n"
		"userValues.length=0;\n"
		"const tableHtml = generateTableFromCSV(csvData);\n"
		"document.getElementById(\'tableContainer\').innerHTML = tableHtml;\n"
		"axis.length=0;\n"
		"temp.length=0;\n"
		"freq.length=0;\n"
		"sleep.length=0;\n"
		"Rwater.length = 0;\n"
		"pressure.length = 0;\n"
		"d1.length=0;\n"
		"d2.length=0;\n"
		"d3 .length=0;\n"
		"d4 .length=0;\n"
		"d5.length=0;\n"
		"d6.length=0;\n"
		"d7.length=0;\n"
		"d8.length=0;\n"
		"d9.length=0;\n"
		"d10.length=0;\n"
		"d11.length=0;\n"
		"d12.length=0;\n"
		"d .length=0;\n"
		"t.length=0;\n"
		"f .length=0;\n"
		"s.length=0;\n"
		"rw.length = 0;\n"
		"pre.length=0;\n"
		"axis.push(userValues.map(row => row.slice(0, 4).map(value => value.toString().replace(\',\', \'.\'))));\n"
		"console.log(\"User Values Array:\",axis);\n"
		"for (let i = 0; i < userValues.length-1; i++) {\n"
		"d1.push(axis[0][i][0]);\n"
		"d2.push(axis[0][i][1]);\n"
		"d3.push(axis[0][i][2]);\n"
		"d4.push(axis[0][i][3]);\n"
		"}\n"
		"for (let i = 0; i < userValues.length-1; i++) {\n"
		"if (i === 0) {\n"
		"d.push([d1[i], d2[i], d3[i], d4[i]]);\n"
		"} else {\n"
		"d.push([Number(d1[i]), Number(d2[i]), Number(d3[i]), Number(d4[i])]);\n"
		"}\n"
		"}\n"
		" var data = google.visualization.arrayToDataTable(d);\n"
		" console.log(\"data is is\",data);\n"
		"var options = {\n"
		"title: \'Accelerometer Data\',\n"
		"curveType: \'function\',\n"
		"legend: { position: \'bottom\' },\n"
		"hAxis: { title: \'Time\' },\n"
		"vAxis: { title: \'Acceleration\' },\n"
		"explorer: { actions: [\'dragToZoom\', \'rightClickToReset\', \'scrollToZoom\'] },\n"
		"pointSize: 5,\n"
		"pointShape: { type: \'circle\', sides: 4, dent: 0.2, rotation: 45 },\n"
		"chartArea: {\n"
		"backgroundColor: \'#f0f0f0\' \n"
		"}\n"
		"};\n"
		"var chart = new google.visualization.LineChart(document.getElementById(\'curve_chart\'));\n"
		"chart.draw(data, options);\n"
		"temp.push(userValues.map(row => {\n"
		"console.log(\'Row:\', row);\n"
		"return [\n"
		"row[0]?.toString()?.replace(\',\', \'.\') || \'\',\n"
		"row[4]?.toString()?.replace(\',\', \'.\') || \'\',\n"
		"row[5]?.toString()?.replace(\',\', \'.\') || \'\',\n"
		"row[6]?.toString()?.replace(\',\', \'.\') || \'\',\n"
		"row[7]?.toString()?.replace(\',\', \'.\') || \'\'\n"
		"];\n"
		"}));\n"
		"console.log(\"User Values temp:\",temp);\n"
		"for (let i = 0; i < userValues.length-1; i++) {\n"
		"d1.push(temp[0][i][0]);\n"
		"d5.push(temp[0][i][1]);\n"
		"d6.push(temp[0][i][2]);\n"
		"d7.push(temp[0][i][3]);\n"
		"d8.push(temp[0][i][4]);\n"
		"}\n"
		"for (let i = 0; i < userValues.length-1; i++) {\n"
		"if(i === 0) {\n"
		"t.push([d1[i], d5[i], d6[i], d7[i], d8[i]]);\n"
		"} else {\n"
		"t.push([Number(d1[i]), Number(d5[i]), Number(d6[i]), Number(d7[i]), Number(d8[i])]);\n"
		"}\n"
		"}\n"
		"console.log(\"temp test data\",t);\n"
		"var tdata = google.visualization.arrayToDataTable(t);\n"
		"var options = {\n"
		"title: \'Temperature Data\',\n"
		"curveType: \'function\',\n"
		"legend: { position: \'bottom\' },\n"
		"hAxis: { title: \'Time\' },\n"
		"vAxis: { title: \'Temperature\', gridlines: { count: 1 }  },\n"
		"pointSize: 5,\n"
		"pointShape: { type: \'circle\', sides: 4, dent: 0.2, rotation: 45 },\n"
		"explorer: { actions: [\'dragToZoom\', \'rightClickToReset\', \'scrollToZoom\'] },\n"
		"};\n"
		"var chart1 = new google.visualization.LineChart(document.getElementById(\'curve_chart2\'));\n"
		"chart1.draw(tdata, options);\n"
		"freq.push(userValues.map(row => [\n"
		"row[0].toString().replace(\',\', \'.\'),\n"
		"row[8]?.toString()?.replace(\',\', \'.\') || \'\'\n"
		"]));\n"
		" for (let i = 0; i < userValues.length; i++) {\n"
		"d1.push(freq[0][i][0]);\n"
		"d9.push(freq[0][i][1]);\n"
		"}\n"
		"for (let i = 0; i < userValues.length; i++) {\n"
		"if (i === 0) {\n"
		"f.push([d1[i], d9[i]]);\n"
		"} else {\n"
		"f.push([Number(d1[i]),Number(d9[i])]);\n"
		"}\n"
		"}\n"
		" var fdata = google.visualization.arrayToDataTable(f);\n"
		" var options = {\n"
		"title: \'Amplitude Data\',\n"
		"curveType: \'function\',\n"
		"legend: { position: \'bottom\' },\n"
		"hAxis: { title: \'Time\' },\n"
		"vAxis: { title: \'Amplitude\' },\n"
		"explorer: { actions: [\'dragToZoom\', \'rightClickToReset\', \'scrollToZoom\'] },\n"
		"pointSize: 5,\n"
		"pointShape: { type: \'circle\', sides: 4, dent: 0.2, rotation: 45 }\n"
		"};\n"
		"var chart2 = new google.visualization.LineChart(document.getElementById(\'curve_chart3\'));\n"
		"chart2.draw(fdata, options);\n"
		"Rwater.push(userValues.map(row => [\n"
		"row[0].toString().replace(\',\', \'.\'),\n"
		"row[9]?.toString()?.replace(\',\', \'.\') || \'\'\n"
		"]));\n"
		" for (let i = 0; i < userValues.length; i++) {\n"
		"d1.push(Rwater[0][i][0]);\n"
		"d10.push(Rwater[0][i][1]);\n"
		"}\n"
		"for (let i = 0; i < userValues.length; i++) {\n"
		"if (i === 0) {\n"
		"rw.push([d1[i], d10[i]]);\n"
		" } else {\n"
		"rw.push([Number(d1[i]),Number(d10[i])]);\n"
		"}\n"
		"}\n"
		"var rwdata = google.visualization.arrayToDataTable(rw);\n"
		"var options = {\n"
		"title: \'rwater Data\',\n"
		"curveType: \'function\',\n"
		"legend: { position: \'bottom\' },\n"
		"hAxis: { title: \'Time\' },\n"
		"vAxis: { title: \'rwater\' },\n"
		"explorer: { actions: [\'dragToZoom\', \'rightClickToReset\', \'scrollToZoom\'] },\n"
		"pointSize: 5,\n"
		"pointShape: { type: \'circle\', sides: 4, dent: 0.2, rotation: 45 }\n"
		" };\n"
		"var chart3 = new google.visualization.LineChart(document.getElementById(\'curve_chart4\'));\n"
		"chart3.draw(rwdata, options);\n"
		"pressure.push(userValues.map(row => [\n"
		"row[0].toString().replace(\',\', \'.\'),\n"
		"row[10]?.toString()?.replace(\',\', \'.\') || \'\'\n"
		"]));\n"
		"for (let i = 0; i < userValues.length; i++) {\n"
		"d1.push(pressure[0][i][0]);\n"
		"d11.push(pressure[0][i][1]);\n"
		"}\n"
		"for (let i = 0; i < userValues.length; i++) {\n"
		"if (i === 0) {\n"
		"pre.push([d1[i], d11[i]]);\n"
		"} else {\n"
		"pre.push([Number(d1[i]),Number(d11[i])]);\n"
		"}\n"
		"}\n"
		"var predata = google.visualization.arrayToDataTable(pre);\n"
		"var options = {\n"
		"title: \'Pressure Data\',\n"
		"curveType: \'function\',\n"
		"legend: { position: \'bottom\' },\n"
		"hAxis: { title: \'Time\' },\n"
		"vAxis: { title: \'Pressure\' },\n"
		"explorer: { actions: [\'dragToZoom\', \'rightClickToReset\', \'scrollToZoom\'] },\n"
		"pointSize: 5,\n"
		"pointShape: { type: \'circle\', sides: 4, dent: 0.2, rotation: 45 }\n"
		"};\n"
		"var chart4 = new google.visualization.LineChart(document.getElementById(\'curve_chart5\'));\n"
		"chart4.draw(predata, options);\n"
		"sleep.push(userValues.map(row => [\n"
		"row[0].toString().replace(\',\', \'.\'),\n"
		"row[11]?.toString()?.replace(\',\', \'.\') || ''\n"
		"]));\n"
		"for (let i = 0; i < userValues.length; i++) {\n"
		"d1.push(sleep[0][i][0]);\n"
		"d12.push(sleep[0][i][1]);\n"
		"}\n"
		"for (let i = 0; i < userValues.length; i++) {\n"
		"if (i === 0) {\n"
		"s.push([d1[i], d12[i]]);\n"
		"} else {\n"
		"s.push([Number(d1[i]),Number(d12[i])]);\n"
		"}\n"
		"}\n"
		"var sdata = google.visualization.arrayToDataTable(s);\n"
		"var options = {\n"
		"title: \'sleep Data\',\n"
		"curveType: \'function\',\n"
		"legend: { position: \'bottom\' },\n"
		"hAxis: { title: \'Time\' },\n"
		"vAxis: { title: \'Sleep\' },\n"
		"explorer: { actions: [\'dragToZoom\', \'rightClickToReset\', \'scrollToZoom\'] },\n"
		"pointSize: 5,\n"
		"pointShape: { type: \'circle\', sides: 4, dent: 0.2, rotation: 45 }\n"
		"};\n"
		"var chart5 = new google.visualization.LineChart(document.getElementById(\'curve_chart6\'));\n"
		"chart5.draw(sdata, options);\n"
		"console.log(\"slp\",sleep);\n"
		"console.log(\"tempArray:\",temp);\n"
		"console.log(\"d1:\",d1);\n"
		"console.log(\"d2:\",d2);\n"
		"console.log(\"d3:\",d3);\n"
		"console.log(\"d4:\",d4);\n"
		"console.log(\"d5:\",d5);\n"
		"console.log(\"d6:\",d6);\n"
		"console.log(\"d7:\",d7);\n"
		"console.log(\"d8:\",d8);\n"
		"console.log(\"d9:\",d8);\n"
		"console.log(\"data:\",data);\n"
		"console.log(\"d is \",d);\n"
		"};\n"
		"reader.readAsText(file);\n"
		"}\n"
		"} \n"
		"const timeData = [Number(d[1])];\n"
		"let clickCount = 0;\n"
		"const clickCountSpan = document.getElementById(\'clickCount\');\n"
		"function playAnimation() {\n"
		"currentTimeIndex = (currentTimeIndex + 1) % d.length;\n"
		"const [time, xAxis, yAxis, zAxis] = d[currentTimeIndex];\n"
		"const transformValue = `rotateX(${xAxis}deg) rotateY(${yAxis}deg) rotateZ(${zAxis}deg)`;\n"
		"document.getElementById(\'model\').style.transform = transformValue;\n"
		"clickCount += 0.5;\n"
		"updateClickCount();\n"
		"}\n"
		"function autoPlayAnimation() {\n"
		"autoPlayIntervalId = setInterval(playAnimation, 1000);\n"
		"}\n"
		"function pauseAnimation() {\n"
		"clearInterval(autoPlayIntervalId);\n"
		"}\n"
		"function generateTableFromCSV(csvData) {\n"
		" lines = csvData.split('\\n');\n"
		"const tableRows = lines.map((line, index) => {\n"
		"const columns = line.split(\';\');\n"
		"userValues.push(columns);\n"
		"if (columns.length > 0) {\n"
		"            firstColumnValues.push(columns[0]);\n"
		"        }\n"
		"const rowTag = index === 0 ? \'th\' : \'td\';\n"
		"return `<tr>${columns.map(column => `<${rowTag}>${column}</${rowTag}>`).join(\'\')}</tr>`;\n"
		"});\n"
		"console.log(`Total rows: ${lines.length}`);\n"
		"    console.log(`First column last value: ${firstColumnValues[firstColumnValues.length - 1]}`);\n"
		"return `<table>${tableRows.join(\'\')}</table>`;\n"
		"resetAnimation();\n"
		"}\n"
		"function resetAnimation() {\n"
		"clearInterval(autoPlayIntervalId);\n"
		"currentTimeIndex = 0;\n"
		"clickCount = 0;\n"
		"updateClickCount();\n"
		"const model = document.getElementById(\'model\');\n"
		"model.style.transform = `rotateX(0deg) rotateY(0deg) rotateZ(0deg)`;\n"
		"drawChart();\n"
		"drawChart2();\n"
		"drawChart3();\n"
		"drawChart4();\n"
		"drawChart5();\n"
		"drawChart6();\n"
		"clickCountSpan.textContent = clickCount;\n"
		"}\n"
		"function updateClickCount() {\n"
		"clickCountSpan.textContent = clickCount;\n"
		"if (clickCount >= (lines.length-3)/2) {\n"
		"                clickCount = 0;\n"
		"            }\n"
		"}\n"
		"function refreshPage() {\n"
		"      location.reload();\n"
		"    }\n"
		"</script>\n"
		"</body>\n"
		"</html>\n";



/**********************************************************************************************************/

/**********************************************USA*******************************************************/
const char USA[] =
		"<!DOCTYPE html>\n"
				"<html lang=\"en\">\n"
				"<head>\n"
				"<meta charset=\"UTF-8\">\n"
				"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
				"<title>Graphical presentation GERMAN format</title>\n"
				"<style>\n"
				"body {\n"
				"margin: 0;\n"
				"padding: 0;\n"
				"display: flex;\n"
				"align-items: center;\n"
				"justify-content: center;\n"
				"height: 100vh;\n"
				"}\n"
				"#outer_box {\n"
				"top: 80%;\n"
				"width: 98%;\n"
				"height: 70vh;\n"
				"overflow: auto;\n"
				"border: 2px solid #000;\n"
				"position: absolute;\n"
				"}\n"
				"#outer_box1 {\n"
				"top: 2%;\n"
				"width: 98%;\n"
				"height: 70vh;\n"
				"overflow: auto;\n"
				"border: 2px solid #000;\n"
				"position: absolute;\n"
				"}\n"
				"#outer_box2 {\n"
				"top: 157%;\n"
				"width: 98%;\n"
				"height: 70vh;\n"
				"overflow: auto;\n"
				"border: 2px solid #000;\n"
				"position: absolute;\n"
				"}\n"
				"#outer_box3 {\n"
				"top: 234%;\n"
				"width: 98%;\n"
				"height: 70vh;\n"
				"overflow: auto;\n"
				"border: 2px solid #000;\n"
				"position: absolute;\n"
				"}\n"
				"#outer_box4 {\n"
				"top: 310%;\n"
				"width: 98%;\n"
				"height: 70vh;\n"
				"overflow: auto;\n"
				"border: 2px solid #000;\n"
				"position: absolute;\n"
				"}\n"
				"#outer_box5 {\n"
				"top: 385%;\n"
				"width: 98%;\n"
				"height: 70vh;\n"
				"overflow: auto;\n"
				"border: 2px solid #000;\n"
				"position: absolute;\n"
				"}\n"
				"#outer_box6 {\n"
				"top: 460%;\n"
				"width: 98%;\n"
				"height: 70vh;\n"
				"overflow: auto;\n"
				"border: 2px solid #000;\n"
				"position: absolute;\n"
				" }\n"
				"#outer_box7 {\n"
				"top: 535%;\n"
				"width: 98%;\n"
				"height: 70vh;\n"
				"overflow: auto;\n"
				"border: 2px solid #000;\n"
				"position: absolute;\n"
				"}\n"
				"#outer_box8 {\n"
				"top: 700%;\n"
				"width: 98%;\n"
				"height: 70vh;\n"
				"overflow: auto;\n"
				"border: 2px solid #000;\n"
				"position: absolute;\n"
				"}\n"
				"#outer_box9 {\n"
				"top: 800%;\n"
				"width: 98%;\n"
				"height: 70vh;\n"
				"overflow: auto;\n"
				"border: 2px solid #000;\n"
				"position: absolute;\n"
				"}\n"
				"#tableContainer {\n"
				"max-height: 600px;\n"
				"overflow-y: auto;\n"
				"}\n"
				"table {\n"
				"border-collapse: collapse;\n"
				"width: 100%;\n"
				"table-layout: fixed;\n"
				"margin-bottom: 20px;\n"
				"}\n"
				"th, td {\n"
				"border: 1px solid #dddddd;\n"
				"text-align: left;\n"
				"padding: 8px;\n"
				"}\n"
				"th{\n"
				"background-color: #f2f2f2;\n"
				"}\n"
				"#curve_chart {\n"
				"top: 70%;\n"
				"width: 98%;\n"
				"height: 70vh;\n"
				"overflow: auto;\n"
				"}\n"
				"#curve_chart2 {\n"
				"top: 70%;\n"
				"width: 98%;\n"
				"height: 70vh;\n"
				"}\n"
				"#curve_chart3 {\n"
				"top: 70%;\n"
				"width: 98%;\n"
				"height: 70vh;\n"
				"}\n"
				"#curve_chart4 {\n"
				"top: 70%;\n"
				"width: 98%;\n"
				"height: 70vh;\n"
				"}\n"
				"#curve_chart5 {\n"
				"top: 70%;\n"
				"width: 98%;\n"
				"height: 70vh;\n"
				"}\n"
				"#curve_chart6 {\n"
				"top: 70%;\n"
				"width: 98%;\n"
				"height: 70vh;\n"
				"}\n"
				"#fileInputContainer {\n"
				"position: absolute;\n"
				"top: 10px;\n"
				"left: 10px;\n"
				"background-color: #fff;\n"
				"padding: 10px;\n"
				"border: 1px solid #ccc;\n"
				"border-radius: 5px;\n"
				"box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\n"
				"}\n"
				"#container {\n"
				"perspective: 800px;\n"
				"width: 300px;\n"
				"height: 300px;\n"
				"position: absolute;\n"
				"top: 30%;\n"
				"left: 40%;\n"
				"}\n"
				"#refresh-button {\n"
				"      padding: 5px 8px;\n"
				"      color: #fff;\n"
				"     border: 1px solid #ccc;\n"
				"background-color: #3498db;   \n"
				"      font-size: 13px;\n"
				"      border-radius: 5px;\n"
				"    }\n"
				"#model {\n"
				"width: 100%;\n"
				"height: 100%;\n"
				"background-color: #3498db;\n"
				"position: absolute;\n"
				"transform-style: preserve-3d;\n"
				"transition: transform 1s ease-in-out;\n"
				"}\n"
				".axis {\n"
				"position: absolute;\n"
				"width: 2px;\n"
				"height: 100px;\n"
				"background-color: #e74c3c;\n"
				"transform-origin: 50% 100%;\n"
				"}\n"
				".axis-x {\n"
				"left: 50%;\n"
				"top: 50%;\n"
				"transform: translateX(-50%) translateY(-100%) rotateX(90deg);\n"
				"background-color: #25161a;\n"
				"}\n"
				".axis-y {\n"
				"left: 50%;\n"
				"top: 50%;\n"
				"transform: translateX(-50%) translateY(-50%)rotateZ(-90deg);\n"
				"background-color: #e74c3c;\n"
				"}\n"
				".axis-z {\n"
				"left: 50%;\n"
				"top: 50%;\n"
				"transform: translateX(-50%) translateY(-50%) rotateZ(0deg);\n"
				"background-color: #68f4c6;\n"
				"}\n"
				"#play-button {\n"
				"position: absolute;\n"
				"top: 100px;\n"
				"left:20%;\n"
				"transform: translateX(-50%);\n"
				"padding: 10px;\n"
				"background-color: #2ecc71;\n"
				"color: #fff;\n"
				"cursor: pointer;\n"
				"}\n"
				"#play-button1 {\n"
				"position: absolute;\n"
				"top: 100px;\n"
				"left: 40%;\n"
				"transform: translateX(-50%);\n"
				"padding: 10px;\n"
				"background-color: #2ecc71;\n"
				"color: #fff;\n"
				"cursor: pointer;\n"
				"}\n"
				"#pause-button {\n"
				"position: absolute;\n"
				"top: 100px;\n"
				"left: 60%;\n"
				"transform: translateX(-50%);\n"
				"padding: 10px;\n"
				"background-color: #e74c3c;\n"
				"color: #fff;\n"
				"cursor: pointer;\n"
				"}\n"
				"#reset-button {\n"
				"position: absolute;\n"
				"top: 100px;\n"
				"left: 80%;\n"
				"transform: translateX(-50%);\n"
				"padding: 10px;\n"
				"background-color: #3498db;\n"
				"color: #fff;\n"
				"cursor: pointer;\n"
				"}\n"
				"</style>\n"
				"</head>\n"
				"<body>\n"
				"<div id=\"outer_box1\">\n"
				"<div id=\"fileInputContainer\">\n"
				"  <button id=\"refresh-button\" onclick=\"refreshPage()\">Refresh</button>\n"
				"<input type=\"file\" id=\"fileInput\" accept=\".csv\">\n"
				"<div id=\"tableContainer\">\n"
				"</div>\n"
				"</div>\n"
				"</div>\n"
				"<div id=\"outer_box\">\n"
				"<div id=\"curve_chart\"></div>\n"
				"</div>\n"
				"<div id=\"outer_box2\">\n"
				"<div id=\"container\">\n"
				"<div id=\"model\">\n"
				"<div class=\"axis axis-x\"></div>\n"
				"<div class=\"axis axis-y\"></div>\n"
				"<div class=\"axis axis-z\"></div>\n"
				"</div>\n"
				"</div>\n"
				"<p align=\"center\"><b>Time:</b> <span style=\"font-weight:bold;\" id=\"clickCount\">0</span></p>\n"
				"<p style=\"bottom: 0; width: 100%; text-align: center;\">\n"
				"<span style=\"color: #25161a;\">(X-AXIS)</span>\n"
				"<span style=\"color: #e74c3c;\">(Y-AXIS)</span>\n"
				"<span style=\"color: #68f4c6;\">(Z-AXIS)</span>\n"
				"</p>\n"
				"<div id=\"play-button\" onclick=\"playAnimation()\">CLICK</div>\n"
				"<div id=\"play-button1\" onclick=\"autoPlayAnimation()\">AUTO_PLAY</div>\n"
				"<div id=\"pause-button\" onclick=\"pauseAnimation()\">PAUSE</div>\n"
				"<div id=\"reset-button\" onclick=\"resetAnimation()\">RESET</div>\n"
				"</div>\n"
				"<div id=\"outer_box3\">\n"
				"<div id=\"curve_chart2\"></div>\n"
				"</div>\n"
				"<div id=\"outer_box4\">\n"
				"<div id=\"curve_chart3\"></div>\n"
				"</div>\n"
				"<div id=\"outer_box5\">\n"
				"<div id=\"curve_chart4\"></div>\n"
				"</div>\n"
				"<div id=\"outer_box6\">\n"
				"<div id=\"curve_chart5\"></div>\n"
				"</div>\n"
				"<div id=\"outer_box7\">\n"
				"<div id=\"curve_chart6\"></div>\n"
				"</div>\n"
				"<script type=\"text/javascript\" src=\"https://www.gstatic.com/charts/loader.js\"></script>\n"
				"<script type=\"text/javascript\">\n"
				"google.charts.load(\'current\', {\'packages\':[\'corechart\']});\n"
				"google.charts.setOnLoadCallback(handleFile);\n"
				"document.getElementById(\'fileInput\').addEventListener(\'change\', handleFile);\n"
				"const firstColumnValues = [];\n"
				"const userValues = [];\n"
				"const axis = [];\n"
				"const temp = [];\n"
				"const freq = [];\n"
				"const sleep = [];\n"
				"const Rwater = [];\n"
				"const pressure = [];\n"
				"let d1 = [];\n"
				"let d2 = [];\n"
				"let d3 = [];\n"
				"let d4 = [];\n"
				"let d5=[];\n"
				"let d6=[];\n"
				"let d7=[];\n"
				"let d8=[];\n"
				"let d9=[];\n"
				"let d10=[];\n"
				"let d11=[];\n"
				"let d12=[];\n"
				"let data = [];\n"
				"let d =[];\n"
				"let t = [];\n"
				"let f =[];\n"
				"let s=[];\n"
				"let rw=[];\n"
				"let pre=[];\n"
				"let lines = []; \n"
				"let currentTimeIndex = 0;\n"
				"function handleFile(event) {\n"
				"const file = event.target.files[0];\n"
				"if (file) {\n"
				"const reader = new FileReader();\n"
				"google.charts.load(\'current\', {\'packages\':[\'corechart\']});\n"
				"google.charts.setOnLoadCallback(handleFile);\n"
				"reader.onload = function(e) {\n"
				"const csvData = e.target.result;\n"
				"userValues.length=0;\n"
				"const tableHtml = generateTableFromCSV(csvData);\n"
				"document.getElementById(\'tableContainer\').innerHTML = tableHtml;\n"
				"axis.length=0;\n"
				"temp.length=0;\n"
				"freq.length=0;\n"
				"sleep.length=0;\n"
				"Rwater.length = 0;\n"
				"pressure.length = 0;\n"
				"d1.length=0;\n"
				"d2.length=0;\n"
				"d3 .length=0;\n"
				"d4 .length=0;\n"
				"d5.length=0;\n"
				"d6.length=0;\n"
				"d7.length=0;\n"
				"d8.length=0;\n"
				"d9.length=0;\n"
				"d10.length=0;\n"
				"d11.length=0;\n"
				"d12.length=0;\n"
				"d .length=0;\n"
				"t.length=0;\n"
				"f .length=0;\n"
				"s.length=0;\n"
				"rw.length = 0;\n"
				"pre.length=0;\n"
				"axis.push(userValues.map(row => row.slice(0, 4).map(value => value.toString().replace(\',\', \'.\'))));\n"
				"console.log(\"User Values Array:\",axis);\n"
				"for (let i = 0; i < userValues.length-1; i++) {\n"
				"d1.push(axis[0][i][0]);\n"
				"d2.push(axis[0][i][1]);\n"
				"d3.push(axis[0][i][2]);\n"
				"d4.push(axis[0][i][3]);\n"
				"}\n"
				"for (let i = 0; i < userValues.length-1; i++) {\n"
				"if (i === 0) {\n"
				"d.push([d1[i], d2[i], d3[i], d4[i]]);\n"
				"} else {\n"
				"d.push([Number(d1[i]), Number(d2[i]), Number(d3[i]), Number(d4[i])]);\n"
				"}\n"
				"}\n"
				" var data = google.visualization.arrayToDataTable(d);\n"
				" console.log(\"data is is\",data);\n"
				"var options = {\n"
				"title: \'Accelerometer Data\',\n"
				"curveType: \'function\',\n"
				"legend: { position: \'bottom\' },\n"
				"hAxis: { title: \'Time\' },\n"
				"vAxis: { title: \'Acceleration\' },\n"
				"explorer: { actions: [\'dragToZoom\', \'rightClickToReset\', \'scrollToZoom\'] },\n"
				"pointSize: 5,\n"
				"pointShape: { type: \'circle\', sides: 4, dent: 0.2, rotation: 45 },\n"
				"chartArea: {\n"
				"backgroundColor: \'#f0f0f0\' \n"
				"}\n"
				"};\n"
				"var chart = new google.visualization.LineChart(document.getElementById(\'curve_chart\'));\n"
				"chart.draw(data, options);\n"
				"temp.push(userValues.map(row => {\n"
				"console.log(\'Row:\', row);\n"
				"return [\n"
				"row[0]?.toString()?.replace(\',\', \'.\') || \'\',\n"
				"row[4]?.toString()?.replace(\',\', \'.\') || \'\',\n"
				"row[5]?.toString()?.replace(\',\', \'.\') || \'\',\n"
				"row[6]?.toString()?.replace(\',\', \'.\') || \'\',\n"
				"row[7]?.toString()?.replace(\',\', \'.\') || \'\'\n"
				"];\n"
				"}));\n"
				"console.log(\"User Values temp:\",temp);\n"
				"for (let i = 0; i < userValues.length-1; i++) {\n"
				"d1.push(temp[0][i][0]);\n"
				"d5.push(temp[0][i][1]);\n"
				"d6.push(temp[0][i][2]);\n"
				"d7.push(temp[0][i][3]);\n"
				"d8.push(temp[0][i][4]);\n"
				"}\n"
				"for (let i = 0; i < userValues.length-1; i++) {\n"
				"if(i === 0) {\n"
				"t.push([d1[i], d5[i], d6[i], d7[i], d8[i]]);\n"
				"} else {\n"
				"t.push([Number(d1[i]), Number(d5[i]), Number(d6[i]), Number(d7[i]), Number(d8[i])]);\n"
				"}\n"
				"}\n"
				"console.log(\"temp test data\",t);\n"
				"var tdata = google.visualization.arrayToDataTable(t);\n"
				"var options = {\n"
				"title: \'Temperature Data\',\n"
				"curveType: \'function\',\n"
				"legend: { position: \'bottom\' },\n"
				"hAxis: { title: \'Time\' },\n"
				"vAxis: { title: \'Temperature\', gridlines: { count: 1 }  },\n"
				"pointSize: 5,\n"
				"pointShape: { type: \'circle\', sides: 4, dent: 0.2, rotation: 45 },\n"
				"explorer: { actions: [\'dragToZoom\', \'rightClickToReset\', \'scrollToZoom\'] },\n"
				"};\n"
				"var chart1 = new google.visualization.LineChart(document.getElementById(\'curve_chart2\'));\n"
				"chart1.draw(tdata, options);\n"
				"freq.push(userValues.map(row => [\n"
				"row[0].toString().replace(\',\', \'.\'),\n"
				"row[8]?.toString()?.replace(\',\', \'.\') || \'\'\n"
				"]));\n"
				" for (let i = 0; i < userValues.length; i++) {\n"
				"d1.push(freq[0][i][0]);\n"
				"d9.push(freq[0][i][1]);\n"
				"}\n"
				"for (let i = 0; i < userValues.length; i++) {\n"
				"if (i === 0) {\n"
				"f.push([d1[i], d9[i]]);\n"
				"} else {\n"
				"f.push([Number(d1[i]),Number(d9[i])]);\n"
				"}\n"
				"}\n"
				" var fdata = google.visualization.arrayToDataTable(f);\n"
				" var options = {\n"
				"title: \'Amplitude Data\',\n"
				"curveType: \'function\',\n"
				"legend: { position: \'bottom\' },\n"
				"hAxis: { title: \'Time\' },\n"
				"vAxis: { title: \'Amplitude\' },\n"
				"explorer: { actions: [\'dragToZoom\', \'rightClickToReset\', \'scrollToZoom\'] },\n"
				"pointSize: 5,\n"
				"pointShape: { type: \'circle\', sides: 4, dent: 0.2, rotation: 45 }\n"
				"};\n"
				"var chart2 = new google.visualization.LineChart(document.getElementById(\'curve_chart3\'));\n"
				"chart2.draw(fdata, options);\n"
				"Rwater.push(userValues.map(row => [\n"
				"row[0].toString().replace(\',\', \'.\'),\n"
				"row[9]?.toString()?.replace(\',\', \'.\') || \'\'\n"
				"]));\n"
				" for (let i = 0; i < userValues.length; i++) {\n"
				"d1.push(Rwater[0][i][0]);\n"
				"d10.push(Rwater[0][i][1]);\n"
				"}\n"
				"for (let i = 0; i < userValues.length; i++) {\n"
				"if (i === 0) {\n"
				"rw.push([d1[i], d10[i]]);\n"
				" } else {\n"
				"rw.push([Number(d1[i]),Number(d10[i])]);\n"
				"}\n"
				"}\n"
				"var rwdata = google.visualization.arrayToDataTable(rw);\n"
				"var options = {\n"
				"title: \'rwater Data\',\n"
				"curveType: \'function\',\n"
				"legend: { position: \'bottom\' },\n"
				"hAxis: { title: \'Time\' },\n"
				"vAxis: { title: \'rwater\' },\n"
				"explorer: { actions: [\'dragToZoom\', \'rightClickToReset\', \'scrollToZoom\'] },\n"
				"pointSize: 5,\n"
				"pointShape: { type: \'circle\', sides: 4, dent: 0.2, rotation: 45 }\n"
				" };\n"
				"var chart3 = new google.visualization.LineChart(document.getElementById(\'curve_chart4\'));\n"
				"chart3.draw(rwdata, options);\n"
				"pressure.push(userValues.map(row => [\n"
				"row[0].toString().replace(\',\', \'.\'),\n"
				"row[10]?.toString()?.replace(\',\', \'.\') || \'\'\n"
				"]));\n"
				"for (let i = 0; i < userValues.length; i++) {\n"
				"d1.push(pressure[0][i][0]);\n"
				"d11.push(pressure[0][i][1]);\n"
				"}\n"
				"for (let i = 0; i < userValues.length; i++) {\n"
				"if (i === 0) {\n"
				"pre.push([d1[i], d11[i]]);\n"
				"} else {\n"
				"pre.push([Number(d1[i]),Number(d11[i])]);\n"
				"}\n"
				"}\n"
				"var predata = google.visualization.arrayToDataTable(pre);\n"
				"var options = {\n"
				"title: \'Pressure Data\',\n"
				"curveType: \'function\',\n"
				"legend: { position: \'bottom\' },\n"
				"hAxis: { title: \'Time\' },\n"
				"vAxis: { title: \'Pressure\' },\n"
				"explorer: { actions: [\'dragToZoom\', \'rightClickToReset\', \'scrollToZoom\'] },\n"
				"pointSize: 5,\n"
				"pointShape: { type: \'circle\', sides: 4, dent: 0.2, rotation: 45 }\n"
				"};\n"
				"var chart4 = new google.visualization.LineChart(document.getElementById(\'curve_chart5\'));\n"
				"chart4.draw(predata, options);\n"
				"sleep.push(userValues.map(row => [\n"
				"row[0].toString().replace(\',\', \'.\'),\n"
				"row[11]?.toString()?.replace(\',\', \'.\') || \'\'\n"
				"]));\n"
				"for (let i = 0; i < userValues.length; i++) {\n"
				"d1.push(sleep[0][i][0]);\n"
				"d12.push(sleep[0][i][1]);\n"
				"}\n"
				"for (let i = 0; i < userValues.length; i++) {\n"
				"if (i === 0) {\n"
				"s.push([d1[i], d12[i]]);\n"
				"} else {\n"
				"s.push([Number(d1[i]),Number(d12[i])]);\n"
				"}\n"
				"}\n"
				"var sdata = google.visualization.arrayToDataTable(s);\n"
				"var options = {\n"
				"title: \'sleep Data\',\n"
				"curveType: \'function\',\n"
				"legend: { position: \'bottom\' },\n"
				"hAxis: { title: \'Time\' },\n"
				"vAxis: { title: \'Sleep\' },\n"
				"explorer: { actions: [\'dragToZoom\', \'rightClickToReset\', \'scrollToZoom\'] },\n"
				"pointSize: 5,\n"
				"pointShape: { type: \'circle\', sides: 4, dent: 0.2, rotation: 45 }\n"
				"};\n"
				"var chart5 = new google.visualization.LineChart(document.getElementById(\'curve_chart6\'));\n"
				"chart5.draw(sdata, options);\n"
				"console.log(\"slp\",sleep);\n"
				"console.log(\"tempArray:\",temp);\n"
				"console.log(\"d1:\",d1);\n"
				"console.log(\"d2:\",d2);\n"
				"console.log(\"d3:\",d3);\n"
				"console.log(\"d4:\",d4);\n"
				"console.log(\"d5:\",d5);\n"
				"console.log(\"d6:\",d6);\n"
				"console.log(\"d7:\",d7);\n"
				"console.log(\"d8:\",d8);\n"
				"console.log(\"d9:\",d8);\n"
				"console.log(\"data:\",data);\n"
				"console.log(\"d is \",d);\n"
				"};\n"
				"reader.readAsText(file);\n"
				"}\n"
				"} \n"
				"const timeData = [Number(d[1])];\n"
				"let clickCount = 0;\n"
				"const clickCountSpan = document.getElementById(\'clickCount\');\n"
				"function playAnimation() {\n"
				"currentTimeIndex = (currentTimeIndex + 1) % d.length;\n"
				"const [time, xAxis, yAxis, zAxis] = d[currentTimeIndex];\n"
				"const transformValue = `rotateX(${xAxis}deg) rotateY(${yAxis}deg) rotateZ(${zAxis}deg)`;\n"
				"document.getElementById(\'model\').style.transform = transformValue;\n"
				"clickCount += 0.5;\n"
				"updateClickCount();\n"
				"}\n"
				"function autoPlayAnimation() {\n"
				"autoPlayIntervalId = setInterval(playAnimation, 1000);\n"
				"}\n"
				"function pauseAnimation() {\n"
				"clearInterval(autoPlayIntervalId);\n"
				"}\n"
				"function generateTableFromCSV(csvData) {\n"
				" lines = csvData.split('\\n');\n"
				"const tableRows = lines.map((line, index) => {\n"
				"const columns = line.split(\',\');\n"
				"userValues.push(columns);\n"
				"if (columns.length > 0) {\n"
				"            firstColumnValues.push(columns[0]);\n"
				"}\n"
				"const rowTag = index === 0 ? \'th\' : \'td\';\n"
				"return `<tr>${columns.map(column => `<${rowTag}>${column}</${rowTag}>`).join(\'\')}</tr>`;\n"
				"});\n"
				"console.log(`Total rows: ${lines.length}`);\n"
				"    console.log(`First column last value: ${firstColumnValues[firstColumnValues.length - 1]}`);\n"
				"return `<table>${tableRows.join(\'\')}</table>`;\n"
				"resetAnimation();\n"
				"}\n"
				"function resetAnimation() {\n"
				"clearInterval(autoPlayIntervalId);\n"
				"currentTimeIndex = 0;\n"
				"clickCount = 0;\n"
				"updateClickCount();\n"
				"const model = document.getElementById(\'model\');\n"
				"model.style.transform = `rotateX(0deg) rotateY(0deg) rotateZ(0deg)`;\n"
				"drawChart();\n"
				"drawChart2();\n"
				"drawChart3();\n"
				"drawChart4();\n"
				"drawChart5();\n"
				"drawChart6();\n"
				"clickCountSpan.textContent = clickCount;\n"
				"}\n"
				"function updateClickCount() {\n"
				"clickCountSpan.textContent = clickCount;\n"
				"if (clickCount >= (lines.length-3)/2) {\n"
				"                clickCount = 0;\n"
				"            }\n"
				"}\n"
				"function refreshPage() {\n"
				"      location.reload();\n"
				"    }\n"
				"</script>\n"
				"</body>\n"
				"</html>\n";


	/**********************************************************************************************************/
